menu:
- {name: 'projects', url: '/projects'}
- {name: 'publications', url: '/publications'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'twitter', link: 'https://twitter.com/fergus_mc'}
- {icon: 'github', link: 'https://github.com/fmcnab'}
- {icon: 'google', link: 'https://scholar.google.com/citations?user=jkIHW8QAAAAJ&hl=en&authuser=1'}
- {icon: 'researchgate', link: 'https://www.researchgate.net/profile/Fergus-Mcnab'}

contacts:
- {name: 'Dr. Fergus M<sup>c</sup>Nab', title: 'Researcher', department: 'Institut f&#252;r Geowissenschaften', institution: 'Universit&#228;t Potsdam', institution_address: 'Karl-Liebknecht-Stra&#223;e 24-25, 14476 Potsdam-Golm, Germany', phone: '+49 331 977 6358', email: 'fergus.mcnab@uni-potsdam.de', image: 'assets/img/UP.jpg'}
